version: '3.9'

services:
  api:
    container_name: api_container
    image: api_image
    build: .
    command: uvicorn --factory app.api:create_app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: on-failure
    
  bot:
    image: api_image
    links:
      - api
    environment:
      - host=api
    env_file:
      - .env
    command: python -m app.bot
    restart: on-failure

