version: '3.9'

services:
  api:
    container_name: api_container
    build: .
    command: uvicorn --factory app.api:create_app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: on-failure
